<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="r5">

    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_width" value="0.1" />
    <xacro:property name="wheel_mass" value="9.1" />

    <xacro:macro name="wheel" params="
        prefix:=' '
        parent_link:='base_link'
        x_offset:='0'
        y_offset:='0'
        z_offset:='0'
        side
        flip">
        <link name="${prefix}${side}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="0.0 0.0 ${(pi/2) * flip}"/>  <!-- Flip if needed (e.g., for left wheels) -->
                <geometry>
                    <mesh filename="file://$(find r5)/meshes/r5_visual/wheel.stl" scale="0.001 0.001 0.001"/>  
                </geometry>
                <material name="grey">
                    <color rgba="1.0 0.5 0.7 1"/>
                </material>
            </visual>
            
            <collision>
                <origin xyz="0 ${flip * wheel_width/2} 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>
            
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="${wheel_mass}"/>
                <inertia
                  ixx="${(wheel_mass/12.0) * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" ixy="0.0" ixz="0.0"
                  iyy="${(wheel_mass/2.0) * (wheel_radius*wheel_radius)}" iyz="0.0"
                  izz="${(wheel_mass/12.0) * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"/>
              </inertial>
        </link>

        <joint name="${prefix}${side}_wheel_joint" type="continuous">
            <origin xyz="${x_offset} ${y_offset} ${z_offset}" rpy="0 0 0"/>
            <parent link="${parent_link}"/>
            <child link="${prefix}${side}_wheel"/>
            <axis xyz="0 1 0"/>
            <limit effort="50.0" velocity="3.0"/>
            <dynamics damping="0.2"/>
        </joint>

        <transmission name="${prefix}${side}_wheel_trans" type="SimpleTransmission">
			<type>transmission_interface/SimpleTransmission</type>
			<actuator name="${prefix}${side}_wheel_motor">
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
			<joint name="${prefix}${side}_wheel_joint">
				<hardwareInterface>VelocityJointInterface</hardwareInterface>
			</joint>
		</transmission>

        <gazebo reference="${prefix}${side}_wheel">
			<mu1 value="1.0"/>
			<mu2 value="0.25"/>
			<kp  value="100000.0" />
			<kd  value="1.0" />
			<fdir1 value="1 0 0"/>
            <visual>
                <material>
                    <ambient>0.2 0.2 0.2 1.0</ambient>
                    <diffuse>0.2 0.2 0.2 1.0</diffuse>
                    <specular>0.2 0.2 0.2 1.0</specular>
                    <emissive>0.0 0.0 0.0 0.0</emissive>
                </material>
            </visual>
        </gazebo>
    </xacro:macro>
</robot>